"""empty message

Revision ID: ffa1b72fdabf
Revises: c8f5f3801a30
Create Date: 2016-06-29 19:44:13.658608

"""

# revision identifiers, used by Alembic.
revision = 'ffa1b72fdabf'
down_revision = 'c8f5f3801a30'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activities', 'sleep_score')
    op.drop_column('activities', 'outlier_tag')
    op.drop_column('activities', 'step_score')
    op.drop_column('activities', 'hr_score')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('hr_score', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('activities', sa.Column('step_score', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('activities', sa.Column('outlier_tag', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('activities', sa.Column('sleep_score', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    ### end Alembic commands ###
